export const errorMessages = {
  e204: "No content!",
  e205: "Reset content!",
  e206: "Partial content!",
  e400: "Bad request!",
  e401: "Unauthorized!",
  e404: "Not found!",
  e500a: "Internal server error!",
  e500b: "Failed to retrieve!",
  e500c: "Failed to create!",
  e500d: "Failed to update!",
  e501: "Not Implemented.",
  e510a: "Extensions to the request are required.",
  e510b: "Extensions to the request are prohibited.",
};
