"use client";

import React, { useRef, useState } from "react";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";

import slugify from "slugify";

import Image from "next/image";

import { cn } from "@/lib/cn-utils";

import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
	Form,
	FormControl,
	FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";

import { roundTo } from "@/lib/round";
import { msgs } from "@/messages";
import { Route } from "@/routes";

import { FileDocument } from "@/interfaces/File";

import styles from "../_files.module.scss";

// https://github.com/colinhacks/zod#nullable
// Here is applied a tricky solution to translate the messages,
// outside React  component on the client side...?
export const FormSchemaGenerator = (messages?: string[], isFileOptional = true) =>
	z.object({
		file: isFileOptional
			? z.any().optional()
			: z.union([
					// z.instanceof(FileList, { message: messages?.shift() }), // This throws an error in the server's log
					// @see https://conform.guide/file-upload
					// @see https://github.com/colinhacks/zod/issues/387#issuecomment-1191390673 // This is the solution
					z.any().refine((files) => files?.length === 1, messages?.shift()),
					z.instanceof(File, {
						message: messages?.shift(),
					}),
			  ]),
		filename: z
			.string()
			.regex(/^[a-zA-Z][.a-zA-Z0-9-_]+$/, {
				message: messages?.shift(),
			})
			.regex(/\.(png|jpg|jpeg|svg|webp|pdf|pptx|xlsx|docx)$/, {
				message: messages?.shift(),
			}),
		description: z.string().optional(),
		/**
		 * Optional file with check
		 * @see https://stackoverflow.com/a/74028632/6543935
		 *
		 * image: z.union([
		 * 			z.string().regex(/\.(png|jpg|jpeg|svg|webp)$/, {
		 * 				message: messages?.shift(),
		 * 			}),
		 * 			z.string().length(0),
		 * 		])
		 * 		.optional()
		 * 		.transform((e) => (e === "" ? undefined : e)),
		 */
	});

export const Files_FormSchema = FormSchemaGenerator();
export type Files_FormSchema = z.infer<typeof Files_FormSchema>;

interface Props {
	className?: string;
	onSubmit: (data: Files_FormSchema) => void;
	submitting?: boolean;
	isContainerDialogOpen?: boolean;
	formData?: FileDocument;
}

const Files_Form: React.FC<Props> = ({ className, onSubmit, submitting = false, formData }) => {
	const t = msgs("FilesFeed");
	const locale = "en";

	const displayImageRef = useRef<HTMLImageElement>(null);
	const [fileToUpload, setFileToUpload] = useState<File | null>(null);

	const FormSchema = FormSchemaGenerator([
		t("formSchema_file"),
		t("formSchema_name"),
		t("form_fileInputDescription"),
		t("formSchema_description"),
	]);

	const form = useForm<Files_FormSchema>({
		resolver: zodResolver(FormSchema),
		defaultValues: {
			file: null,
			filename: "",
			description: "",
		},
		values: {
			file: null,
			filename: formData?.filename ?? "",
			description: formData?.metadata?.description ?? "",
		},
	});

	const handleInputFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		const file = event.target.files?.item(0) ?? null;

		if (file) {
			const filename = slugify(
				file.name.replace(/[^\.a-zA-Z0-9_-]/g, "-").replace(/^[^a-zA-Z]/g, ""),
				{
					lower: false,
					remove: /[*+~()'"!:@]/g,
					locale: "en",
				}
			);

			if (!filename.match(/\.(png|jpg|jpeg|svg|webp|pdf|pptx|xlsx|docx)$/)) {
				form.setError("file", {
					type: "manual",
					message: t("form_fileInputDescription"),
				});

				return;
			} else {
				form.clearErrors("file");
			}

			if (displayImageRef?.current) {
				// First remove the "srcset" attribute, generated by the Next.js <Image> component
				displayImageRef.current?.setAttribute("srcset", "");

				// Then set new "src" attribute
				if (filename.match(/\.(png|jpg|jpeg|svg|webp)$/)) {
					displayImageRef.current?.setAttribute("src", URL.createObjectURL(file));
				} else if (filename.match(/\.(pdf|pptx|xlsx|docx)$/)) {
					displayImageRef.current?.setAttribute(
						"src",
						`${Route.assets.MIME_TYPE}/${filename.split(".").pop()}.png`
					);
				}
			}

			const modifiedDate = new Date(file.lastModified).toLocaleString(locale);
			const fileSizeKb = roundTo(file.size / 1000, 1);

			if (!formData) {
				form.setValue("filename", filename);
				form.setValue("description", `${modifiedDate} ~${fileSizeKb}Kb`);
			} else if (formData.filename.split(".").at(-1) !== filename.split(".").at(-1)) {
				const newFileName = `${formData.filename.split(".").slice(0, -1).join(".")}.${filename
					.split(".")
					.at(-1)}`;

				form.setValue("filename", newFileName);
			}

			setFileToUpload(file);
		}
	};

	const handleSubmit = async (data: Files_FormSchema) => {
		if (!fileToUpload && !formData) {
			form.setError("file", {
				type: "manual",
				message: t("formSchema_file"),
			});

			return;
		}

		data.file = fileToUpload;

		onSubmit(data);
	};

	const fileUri = formData
		? formData.filename.match(/\.(pdf|pptx|xlsx|docx)$/)
			? `${Route.assets.MIME_TYPE}/${formData.filename.split(".").pop()}.png`
			: `${Route.api.FILES}/${formData?._id.toString()}/${formData?.filename}?v=${new Date(
					formData.uploadDate
			  ).getTime()}`
		: Route.assets.IMAGE_PLACEHOLDER;

	return (
		<Form {...form}>
			<form className={cn(styles.form, className)} onSubmit={form.handleSubmit(handleSubmit)}>
				<FormItem>
					<FormLabel
						className={form.formState.errors.file ? "text-destructive" : "text-foreground"}
						htmlFor="file-input"
					>
						{t("form_fileInput")}
					</FormLabel>

					<FormControl>
						<div className={cn(styles.fileInputWrapper)}>
							<Input
								id="file-input"
								{...form.register("file")}
								accept="image/*, .pdf, .pptx, .xlsx, .docx"
								className={cn(styles.fileInput)}
								type="file"
								onChange={handleInputFileChange}
							/>
						</div>
					</FormControl>

					<FormDescription>{t("form_fileInputDescription")}</FormDescription>

					{form.formState.errors.file && (
						<p className="text-sm font-medium text-destructive">
							{String(form.formState.errors.file.message)}
						</p>
					)}
				</FormItem>

				<FormField
					control={form.control}
					name="filename"
					render={({ field }) => (
						<FormItem>
							<FormLabel>{t("form_fileName")}</FormLabel>
							<FormControl>
								<Input placeholder={t("form_fileNamePlaceholder")} {...field} />
							</FormControl>
							<FormDescription>{t("form_fileNameDescription")}</FormDescription>
							<FormMessage />
						</FormItem>
					)}
				/>

				<FormField
					control={form.control}
					name="description"
					render={({ field }) => (
						<FormItem className="mr-56">
							<FormLabel>{t("form_fileDescription")}</FormLabel>
							<FormControl>
								<Input placeholder={t("form_fileDescriptionPlaceholder")} {...field} />
							</FormControl>
							<FormDescription>{t("form_fileDescriptionDescription")}</FormDescription>
							<FormMessage />
						</FormItem>
					)}
				/>
				<Button type="submit">
					{submitting ? t("form_btn_submitting") : t("form_btn_submit")}
				</Button>
				<div className="absolute right-0 bottom-0 w-52 h-48 rounded-md overflow-hidden">
					<Image
						ref={displayImageRef}
						alt="Display image before upload"
						className="object-cover w-full h-full rounded-md"
						height="0"
						sizes="208px"
						src={fileUri}
						width="0"
					/>
				</div>
			</form>
		</Form>
	);
};

export default Files_Form;
