import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ThemesProvider from "@/contexts/themes-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemesProvider>{children}</ThemesProvider>
      </body>
    </html>
  );
};

export default RootLayout;
