import { poppins, unicephalon } from "@/app/fonts";
import BackToTop from "@/components/layouts/footer/BackToTop";
import MainLayout from "@/components/layouts/main-layout";
import { Toaster } from "@/components/ui/toaster";
import { AppContextProvider } from "@/contexts/AppContext";
import AuthSessionProvider from "@/contexts/AuthSessionProvider";
import ThemesProvider from "@/contexts/ThemesProvider";

import "app/_styles/globals-file-card.scss";
import "app/_styles/globals-syntax-highlight.scss";
import "app/_styles/globals.css";

import {
  APP_AUTHOR,
  APP_AUTHOR_URL,
  APP_NAME,
  BASE_URL,
  META_DESCRIPTION,
  META_TITLE,
  OG_IMAGE,
  OG_IMAGE_ALT,
} from "./_layout.constants";

import type { Metadata, Viewport } from "next";

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#548ada" },
    { media: "(prefers-color-scheme: dark)", color: "#548ada" },
    { color: "#548ada", media: "(prefers-color-scheme: light)" },
    { color: "#548ada", media: "(prefers-color-scheme: dark)" },
  ],
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  // --- Your Existing Metadata ---
  title: META_TITLE,
  description: META_DESCRIPTION,
  metadataBase: new URL(BASE_URL),
  alternates: {
    canonical: BASE_URL,
  },
  openGraph: {
    title: META_TITLE,
    description: META_DESCRIPTION,
    url: BASE_URL,
    siteName: APP_NAME,
    images: [
      {
        url: OG_IMAGE,
        width: 1200,
        height: 630,
        alt: OG_IMAGE_ALT,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image", // or "summary", "app", "player"
    title: META_TITLE,
    description: META_DESCRIPTION,
    images: [OG_IMAGE],
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // --- PWA AND SEO METADATA (MERGED) ---
  applicationName: APP_NAME,
  authors: [{ name: APP_AUTHOR, url: APP_AUTHOR_URL }],
  keywords: [
    "image",
    "image optimizer",
    "image converter",
    "image optimization",
    "image format",
    "webp",
    "avif",
  ],

  // Links to the manifest file that will be generated by `app/manifest.ts`
  manifest: "/manifest.webmanifest",

  // Updated icons object for PWA and favicon
  icons: {
    // Favicon for browser tabs (uses your general SVG for modern browsers)
    icon: { rel: "icon", url: "/favicon.svg", type: "image/svg+xml" },
    // Apple Touch Icon for iOS home screen (uses your highest resolution icon)
    apple: "/icons/apple-touch-icon-180x180.png",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.className} ${unicephalon.variable}`}>
        <ThemesProvider>
          <AuthSessionProvider>
            <AppContextProvider>
              {/* <RecaptchaContextProvider> */}
              <MainLayout>{children}</MainLayout>
              <Toaster />
              <BackToTop />
              {/* </RecaptchaContextProvider> */}
            </AppContextProvider>
          </AuthSessionProvider>
          {/* {process.env.VERCEL_ENV === "production" && <Analytics />} */}
        </ThemesProvider>
      </body>
    </html>
  );
};

export default RootLayout;
