// This file is generated by scripts/generate-icon-map.ts

const iconsMap = {
	"it_apache-text": {
		name: "it_apache-text",
		uri: {
			light: "/assets/icons/it/apache-text.png",
			dark: "/assets/icons/it/apache-text.svg",
		},
		info: {
			height: 800,
			width: 800,
			type: "png",
			ratio: 1,
		},
	},
	"it_apache-wide": {
		name: "it_apache-wide",
		uri: {
			light: "/assets/icons/it/apache-wide.png",
			dark: "/assets/icons/it/apache-wide.png",
		},
		info: {
			height: 274,
			width: 302,
			type: "png",
			ratio: 1.1,
		},
	},
	it_apache: {
		name: "it_apache",
		uri: {
			light: "/assets/icons/it/apache.svg",
			dark: "/assets/icons/it/apache.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_autohotkey-ahk-icon": {
		name: "it_autohotkey-ahk-icon",
		uri: {
			light: "/assets/icons/it/autohotkey-ahk-icon.svg",
			dark: "/assets/icons/it/autohotkey-ahk-icon.svg",
		},
		info: {
			height: 48,
			width: 48,
			type: "svg",
			ratio: 1,
		},
	},
	it_babel2: {
		name: "it_babel2",
		uri: {
			light: "/assets/icons/it/babel2-light.svg",
			dark: "/assets/icons/it/babel2-light.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_bash-logo-colored": {
		name: "it_bash-logo-colored",
		uri: {
			light: "/assets/icons/it/bash-logo-colored.svg",
			dark: "/assets/icons/it/bash-logo-colored.svg",
		},
		info: {
			height: 2500,
			width: 2269,
			type: "svg",
			ratio: 0.91,
		},
	},
	"it_bootstrap-5-icon": {
		name: "it_bootstrap-5-icon",
		uri: {
			light: "/assets/icons/it/bootstrap-5-icon.svg",
			dark: "/assets/icons/it/bootstrap-5-icon.svg",
		},
		info: {
			height: 1992,
			width: 2500,
			type: "svg",
			ratio: 1.26,
		},
	},
	"it_bootstrap-icon": {
		name: "it_bootstrap-icon",
		uri: {
			light: "/assets/icons/it/bootstrap-icon.svg",
			dark: "/assets/icons/it/bootstrap-icon.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	"it_builder-io": {
		name: "it_builder-io",
		uri: {
			light: "/assets/icons/it/builder-io.svg",
			dark: "/assets/icons/it/builder-io.svg",
		},
		info: {
			height: 293,
			width: 256,
			type: "svg",
			ratio: 0.87,
		},
	},
	it_cloudflare: {
		name: "it_cloudflare",
		uri: {
			light: "/assets/icons/it/cloudflare.svg",
			dark: "/assets/icons/it/cloudflare.svg",
		},
		info: {
			height: 1504,
			width: 1556,
			type: "svg",
			ratio: 1.03,
		},
	},
	it_composer: {
		name: "it_composer",
		uri: {
			light: "/assets/icons/it/composer.svg",
			dark: "/assets/icons/it/composer.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_containers: {
		name: "it_containers",
		uri: {
			light: "/assets/icons/it/containers.svg",
			dark: "/assets/icons/it/containers.svg",
		},
		info: {
			height: 153,
			width: 166,
			type: "svg",
			ratio: 1.08,
		},
	},
	it_css: {
		name: "it_css",
		uri: {
			light: "/assets/icons/it/css.svg",
			dark: "/assets/icons/it/css.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_digitalocean-icon": {
		name: "it_digitalocean-icon",
		uri: {
			light: "/assets/icons/it/digitalocean-icon.svg",
			dark: "/assets/icons/it/digitalocean-icon.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	it_docker: {
		name: "it_docker",
		uri: {
			light: "/assets/icons/it/docker.svg",
			dark: "/assets/icons/it/docker.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_docker1: {
		name: "it_docker1",
		uri: {
			light: "/assets/icons/it/docker1.svg",
			dark: "/assets/icons/it/docker1.svg",
		},
		info: {
			height: 2500,
			width: 2269,
			type: "svg",
			ratio: 0.91,
		},
	},
	it_docker2: {
		name: "it_docker2",
		uri: {
			light: "/assets/icons/it/docker2.svg",
			dark: "/assets/icons/it/docker2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_dockertest: {
		name: "it_dockertest",
		uri: {
			light: "/assets/icons/it/dockertest.svg",
			dark: "/assets/icons/it/dockertest.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_dockertest2: {
		name: "it_dockertest2",
		uri: {
			light: "/assets/icons/it/dockertest2.svg",
			dark: "/assets/icons/it/dockertest2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_figma: {
		name: "it_figma",
		uri: {
			light: "/assets/icons/it/figma.svg",
			dark: "/assets/icons/it/figma.svg",
		},
		info: {
			height: 2500,
			width: 1667,
			type: "svg",
			ratio: 0.67,
		},
	},
	"it_framer-motion-seeklogo": {
		name: "it_framer-motion-seeklogo",
		uri: {
			light: "/assets/icons/it/framer-motion-seeklogo.svg",
			dark: "/assets/icons/it/framer-motion-seeklogo.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	"it_git-icon": {
		name: "it_git-icon",
		uri: {
			light: "/assets/icons/it/git-icon.svg",
			dark: "/assets/icons/it/git-icon.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	it_github: {
		name: "it_github",
		uri: {
			light: "/assets/icons/it/github-light.svg",
			dark: "/assets/icons/it/github-dark.svg",
		},
		info: {
			height: 512,
			width: 496,
			type: "svg",
			ratio: 0.97,
		},
	},
	it_gitlab: {
		name: "it_gitlab",
		uri: {
			light: "/assets/icons/it/gitlab.svg",
			dark: "/assets/icons/it/gitlab.svg",
		},
		info: {
			height: 2305,
			width: 2500,
			type: "svg",
			ratio: 1.08,
		},
	},
	"it_google-reCAPTCHA-icon-big": {
		name: "it_google-reCAPTCHA-icon-big",
		uri: {
			light: "/assets/icons/it/google-reCAPTCHA-icon-big.svg",
			dark: "/assets/icons/it/google-reCAPTCHA-icon-big.svg",
		},
		info: {
			height: 2494,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	"it_google-reCAPTCHA-icon-small": {
		name: "it_google-reCAPTCHA-icon-small",
		uri: {
			light: "/assets/icons/it/google-reCAPTCHA-icon-small.svg",
			dark: "/assets/icons/it/google-reCAPTCHA-icon-small.svg",
		},
		info: {
			height: 130,
			width: 150,
			type: "svg",
			ratio: 1.15,
		},
	},
	it_html: {
		name: "it_html",
		uri: {
			light: "/assets/icons/it/html.svg",
			dark: "/assets/icons/it/html.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_javascript: {
		name: "it_javascript",
		uri: {
			light: "/assets/icons/it/javascript.svg",
			dark: "/assets/icons/it/javascript.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_jquery: {
		name: "it_jquery",
		uri: {
			light: "/assets/icons/it/jquery-light.svg",
			dark: "/assets/icons/it/jquery-dark.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_laravel-alt": {
		name: "it_laravel-alt",
		uri: {
			light: "/assets/icons/it/laravel-alt.svg",
			dark: "/assets/icons/it/laravel-alt.svg",
		},
		info: {
			height: 1713,
			width: 2500,
			type: "svg",
			ratio: 1.46,
		},
	},
	it_laravel: {
		name: "it_laravel",
		uri: {
			light: "/assets/icons/it/laravel.svg",
			dark: "/assets/icons/it/laravel.svg",
		},
		info: {
			height: 2500,
			width: 2418,
			type: "svg",
			ratio: 0.97,
		},
	},
	"it_less-logo": {
		name: "it_less-logo",
		uri: {
			light: "/assets/icons/it/less-logo.svg",
			dark: "/assets/icons/it/less-logo.svg",
		},
		info: {
			height: 480,
			width: 480,
			type: "svg",
			ratio: 1,
		},
	},
	"it_less-sq": {
		name: "it_less-sq",
		uri: {
			light: "/assets/icons/it/less-sq.svg",
			dark: "/assets/icons/it/less-sq.svg",
		},
		info: {
			height: 16,
			width: 13,
			type: "svg",
			ratio: 0.81,
		},
	},
	it_less: {
		name: "it_less",
		uri: {
			light: "/assets/icons/it/less.svg",
			dark: "/assets/icons/it/less.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_lib-virt": {
		name: "it_lib-virt",
		uri: {
			light: "/assets/icons/it/lib-virt.svg",
			dark: "/assets/icons/it/lib-virt.svg",
		},
		info: {
			height: 292,
			width: 343,
			type: "svg",
			ratio: 1.17,
		},
	},
	"it_linux-0": {
		name: "it_linux-0",
		uri: {
			light: "/assets/icons/it/linux-0.svg",
			dark: "/assets/icons/it/linux-0.svg",
		},
		info: {
			height: 37,
			width: 37,
			type: "svg",
			ratio: 1,
		},
	},
	"it_linux-1": {
		name: "it_linux-1",
		uri: {
			light: "/assets/icons/it/linux-1.png",
			dark: "/assets/icons/it/linux-1.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"it_linux-1x128": {
		name: "it_linux-1x128",
		uri: {
			light: "/assets/icons/it/linux-1x128.png",
			dark: "/assets/icons/it/linux-1x128.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"it_linux-2": {
		name: "it_linux-2",
		uri: {
			light: "/assets/icons/it/linux-2.png",
			dark: "/assets/icons/it/linux-2.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"it_linux-2x128": {
		name: "it_linux-2x128",
		uri: {
			light: "/assets/icons/it/linux-2x128.png",
			dark: "/assets/icons/it/linux-2x128.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"it_linux-3": {
		name: "it_linux-3",
		uri: {
			light: "/assets/icons/it/linux-3.png",
			dark: "/assets/icons/it/linux-3.png",
		},
		info: {
			height: 271,
			width: 300,
			type: "png",
			ratio: 1.11,
		},
	},
	it_lua: {
		name: "it_lua",
		uri: {
			light: "/assets/icons/it/lua.svg",
			dark: "/assets/icons/it/lua.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_mariadb: {
		name: "it_mariadb",
		uri: {
			light: "/assets/icons/it/mariadb.svg",
			dark: "/assets/icons/it/mariadb.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_markdown: {
		name: "it_markdown",
		uri: {
			light: "/assets/icons/it/markdown.svg",
			dark: "/assets/icons/it/markdown.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_material-ui": {
		name: "it_material-ui",
		uri: {
			light: "/assets/icons/it/material-ui.svg",
			dark: "/assets/icons/it/material-ui.svg",
		},
		info: {
			height: 2185,
			width: 2500,
			type: "svg",
			ratio: 1.14,
		},
	},
	"it_mediawiki-v0": {
		name: "it_mediawiki-v0",
		uri: {
			light: "/assets/icons/it/mediawiki-v0.svg",
			dark: "/assets/icons/it/mediawiki-v0.svg",
		},
		info: {
			height: 125,
			width: 125,
			type: "svg",
			ratio: 1,
		},
	},
	"it_mediawiki-v1": {
		name: "it_mediawiki-v1",
		uri: {
			light: "/assets/icons/it/mediawiki-v1.svg",
			dark: "/assets/icons/it/mediawiki-v1.svg",
		},
		info: {
			height: 122,
			width: 125,
			type: "svg",
			ratio: 1.02,
		},
	},
	"it_mediawiki-v2": {
		name: "it_mediawiki-v2",
		uri: {
			light: "/assets/icons/it/mediawiki-v2.svg",
			dark: "/assets/icons/it/mediawiki-v2.svg",
		},
		info: {
			height: 100,
			width: 100,
			type: "svg",
			ratio: 1,
		},
	},
	"it_mod-security": {
		name: "it_mod-security",
		uri: {
			light: "/assets/icons/it/mod-security.png",
			dark: "/assets/icons/it/mod-security.png",
		},
		info: {
			height: 48,
			width: 48,
			type: "png",
			ratio: 1,
		},
	},
	it_mongo: {
		name: "it_mongo",
		uri: {
			light: "/assets/icons/it/mongo.svg",
			dark: "/assets/icons/it/mongo.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_mongoose-green-border": {
		name: "it_mongoose-green-border",
		uri: {
			light: "/assets/icons/it/mongoose-green-border.svg",
			dark: "/assets/icons/it/mongoose-green-border.svg",
		},
		info: {
			height: 120,
			width: 114,
			type: "svg",
			ratio: 0.95,
		},
	},
	"it_mongoose-green-text": {
		name: "it_mongoose-green-text",
		uri: {
			light: "/assets/icons/it/mongoose-green-text.svg",
			dark: "/assets/icons/it/mongoose-green-text.svg",
		},
		info: {
			height: 103,
			width: 488,
			type: "svg",
			ratio: 4.74,
		},
	},
	"it_mongoose-green": {
		name: "it_mongoose-green",
		uri: {
			light: "/assets/icons/it/mongoose-green.svg",
			dark: "/assets/icons/it/mongoose-green.svg",
		},
		info: {
			height: 99,
			width: 87,
			type: "svg",
			ratio: 0.88,
		},
	},
	"it_mongoosejs-favicon": {
		name: "it_mongoosejs-favicon",
		uri: {
			light: "/assets/icons/it/mongoosejs-favicon.png",
			dark: "/assets/icons/it/mongoosejs-favicon.png",
		},
		info: {
			height: 144,
			width: 144,
			type: "png",
			ratio: 1,
		},
	},
	it_mongoosejs: {
		name: "it_mongoosejs",
		uri: {
			light: "/assets/icons/it/mongoosejs.png",
			dark: "/assets/icons/it/mongoosejs.png",
		},
		info: {
			height: 200,
			width: 200,
			type: "png",
			ratio: 1,
		},
	},
	"it_mysql-square": {
		name: "it_mysql-square",
		uri: {
			light: "/assets/icons/it/mysql-square.svg",
			dark: "/assets/icons/it/mysql-square.svg",
		},
		info: {
			height: 48,
			width: 48,
			type: "svg",
			ratio: 1,
		},
	},
	it_mysql: {
		name: "it_mysql",
		uri: {
			light: "/assets/icons/it/mysql.svg",
			dark: "/assets/icons/it/mysql.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_new-php-logo": {
		name: "it_new-php-logo",
		uri: {
			light: "/assets/icons/it/new-php-logo.svg",
			dark: "/assets/icons/it/new-php-logo.svg",
		},
		info: {
			height: 384,
			width: 711,
			type: "svg",
			ratio: 1.85,
		},
	},
	"it_nextjs-icon": {
		name: "it_nextjs-icon",
		uri: {
			light: "/assets/icons/it/nextjs-icon-light.svg",
			dark: "/assets/icons/it/nextjs-icon-dark.svg",
		},
		info: {
			height: 180,
			width: 180,
			type: "svg",
			ratio: 1,
		},
	},
	it_nginx: {
		name: "it_nginx",
		uri: {
			light: "/assets/icons/it/nginx.svg",
			dark: "/assets/icons/it/nginx.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_node-js-seeklogo.com": {
		name: "it_node-js-seeklogo.com",
		uri: {
			light: "/assets/icons/it/node-js-seeklogo.com.svg",
			dark: "/assets/icons/it/node-js-seeklogo.com.svg",
		},
		info: {
			height: 292,
			width: 256,
			type: "svg",
			ratio: 0.88,
		},
	},
	it_node: {
		name: "it_node",
		uri: {
			light: "/assets/icons/it/node.svg",
			dark: "/assets/icons/it/node.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_node2: {
		name: "it_node2",
		uri: {
			light: "/assets/icons/it/node2.svg",
			dark: "/assets/icons/it/node2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_nodejs-1": {
		name: "it_nodejs-1",
		uri: {
			light: "/assets/icons/it/nodejs-1.svg",
			dark: "/assets/icons/it/nodejs-1.svg",
		},
		info: {
			height: 1533,
			width: 2500,
			type: "svg",
			ratio: 1.63,
		},
	},
	"it_notepad-plus-plus": {
		name: "it_notepad-plus-plus",
		uri: {
			light: "/assets/icons/it/notepad-plus-plus.svg",
			dark: "/assets/icons/it/notepad-plus-plus.svg",
		},
		info: {
			height: 2042,
			width: 2500,
			type: "svg",
			ratio: 1.22,
		},
	},
	"it_notepad-pp": {
		name: "it_notepad-pp",
		uri: {
			light: "/assets/icons/it/notepad-pp.svg",
			dark: "/assets/icons/it/notepad-pp.svg",
		},
		info: {
			height: 256,
			width: 256,
			type: "svg",
			ratio: 1,
		},
	},
	"it_php-fa": {
		name: "it_php-fa",
		uri: {
			light: "/assets/icons/it/php-fa-light.svg",
			dark: "/assets/icons/it/php-fa-dark.svg",
		},
		info: {
			height: 16,
			width: 20,
			type: "svg",
			ratio: 1.25,
		},
	},
	"it_php-logo-bright": {
		name: "it_php-logo-bright",
		uri: {
			light: "/assets/icons/it/php-logo-bright.webp",
			dark: "/assets/icons/it/php-logo-bright.webp",
		},
		info: {
			height: 159,
			width: 300,
			type: "webp",
			ratio: 1.89,
		},
	},
	"it_php-logo-flat": {
		name: "it_php-logo-flat",
		uri: {
			light: "/assets/icons/it/php-logo-flat.webp",
			dark: "/assets/icons/it/php-logo-flat.webp",
		},
		info: {
			height: 156,
			width: 246,
			type: "webp",
			ratio: 1.58,
		},
	},
	"it_php-logo": {
		name: "it_php-logo",
		uri: {
			light: "/assets/icons/it/php-logo.svg",
			dark: "/assets/icons/it/php-logo.svg",
		},
		info: {
			height: 380,
			width: 600,
			type: "svg",
			ratio: 1.58,
		},
	},
	"it_php-square-big-png": {
		name: "it_php-square-big-png",
		uri: {
			light: "/assets/icons/it/php-square-big-png.png",
			dark: "/assets/icons/it/php-square-big-png.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"it_php-square-big": {
		name: "it_php-square-big",
		uri: {
			light: "/assets/icons/it/php-square-big.webp",
			dark: "/assets/icons/it/php-square-big.webp",
		},
		info: {
			height: 128,
			width: 128,
			type: "webp",
			ratio: 1,
		},
	},
	"it_php-square": {
		name: "it_php-square",
		uri: {
			light: "/assets/icons/it/php-square.webp",
			dark: "/assets/icons/it/php-square.webp",
		},
		info: {
			height: 256,
			width: 256,
			type: "webp",
			ratio: 1,
		},
	},
	it_php: {
		name: "it_php",
		uri: {
			light: "/assets/icons/it/php.svg",
			dark: "/assets/icons/it/php.svg",
		},
		info: {
			height: 24,
			width: 32,
			type: "svg",
			ratio: 1.33,
		},
	},
	it_php2: {
		name: "it_php2",
		uri: {
			light: "/assets/icons/it/php2.svg",
			dark: "/assets/icons/it/php2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_php3: {
		name: "it_php3",
		uri: {
			light: "/assets/icons/it/php3.svg",
			dark: "/assets/icons/it/php3.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_portainer: {
		name: "it_portainer",
		uri: {
			light: "/assets/icons/it/portainer.svg",
			dark: "/assets/icons/it/portainer.svg",
		},
		info: {
			height: 2500,
			width: 1788,
			type: "svg",
			ratio: 0.72,
		},
	},
	it_prettier: {
		name: "it_prettier",
		uri: {
			light: "/assets/icons/it/prettier-light.svg",
			dark: "/assets/icons/it/prettier.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_prisma: {
		name: "it_prisma",
		uri: {
			light: "/assets/icons/it/prisma-light.svg",
			dark: "/assets/icons/it/prisma.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_proxmox-ve": {
		name: "it_proxmox-ve",
		uri: {
			light: "/assets/icons/it/proxmox-ve.png",
			dark: "/assets/icons/it/proxmox-ve.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	it_react: {
		name: "it_react",
		uri: {
			light: "/assets/icons/it/react-light.svg",
			dark: "/assets/icons/it/react-dark.svg",
		},
		info: {
			height: 3619,
			width: 3619,
			type: "svg",
			ratio: 1,
		},
	},
	it_redis: {
		name: "it_redis",
		uri: {
			light: "/assets/icons/it/redis.svg",
			dark: "/assets/icons/it/redis.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	it_sass: {
		name: "it_sass",
		uri: {
			light: "/assets/icons/it/sass.svg",
			dark: "/assets/icons/it/sass.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_scss: {
		name: "it_scss",
		uri: {
			light: "/assets/icons/it/scss.svg",
			dark: "/assets/icons/it/scss.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_shadcn-ui": {
		name: "it_shadcn-ui",
		uri: {
			light: "/assets/icons/it/shadcn-ui-light.svg",
			dark: "/assets/icons/it/shadcn-ui-dark.svg",
		},
		info: {
			height: 256,
			width: 256,
			type: "svg",
			ratio: 1,
		},
	},
	it_sql: {
		name: "it_sql",
		uri: {
			light: "/assets/icons/it/sql.svg",
			dark: "/assets/icons/it/sql.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_tailwind-css-blue": {
		name: "it_tailwind-css-blue",
		uri: {
			light: "/assets/icons/it/tailwind-css-blue.svg",
			dark: "/assets/icons/it/tailwind-css-blue.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	"it_tailwind-css-green": {
		name: "it_tailwind-css-green",
		uri: {
			light: "/assets/icons/it/tailwind-css-green.svg",
			dark: "/assets/icons/it/tailwind-css-green.svg",
		},
		info: {
			height: 2500,
			width: 2500,
			type: "svg",
			ratio: 1,
		},
	},
	it_truenas: {
		name: "it_truenas",
		uri: {
			light: "/assets/icons/it/truenas.svg",
			dark: "/assets/icons/it/truenas.svg",
		},
		info: {
			height: 90,
			width: 90,
			type: "svg",
			ratio: 1,
		},
	},
	it_typescript: {
		name: "it_typescript",
		uri: {
			light: "/assets/icons/it/typescript.svg",
			dark: "/assets/icons/it/typescript.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_vercel-icon": {
		name: "it_vercel-icon",
		uri: {
			light: "/assets/icons/it/vercel-icon-light.svg",
			dark: "/assets/icons/it/vercel-icon-dark.svg",
		},
		info: {
			height: 1200,
			width: 1155,
			type: "svg",
			ratio: 0.96,
		},
	},
	"it_visual-studio-code": {
		name: "it_visual-studio-code",
		uri: {
			light: "/assets/icons/it/visual-studio-code.svg",
			dark: "/assets/icons/it/visual-studio-code.svg",
		},
		info: {
			height: 2455,
			width: 2500,
			type: "svg",
			ratio: 1.02,
		},
	},
	"it_wordpress-blue-logo": {
		name: "it_wordpress-blue-logo",
		uri: {
			light: "/assets/icons/it/wordpress-blue-logo.svg",
			dark: "/assets/icons/it/wordpress-blue-logo.svg",
		},
		info: {
			height: 123,
			width: 123,
			type: "svg",
			ratio: 1,
		},
	},
	"it_wordpress-orange": {
		name: "it_wordpress-orange",
		uri: {
			light: "/assets/icons/it/wordpress-orange.svg",
			dark: "/assets/icons/it/wordpress-orange.svg",
		},
		info: {
			height: 800,
			width: 800,
			type: "svg",
			ratio: 1,
		},
	},
	"it_zod-logo": {
		name: "it_zod-logo",
		uri: {
			light: "/assets/icons/it/zod-logo.svg",
			dark: "/assets/icons/it/zod-logo.svg",
		},
		info: {
			height: 1080,
			width: 1080,
			type: "svg",
			ratio: 1,
		},
	},
	"me_auto-lisp-scripting-language": {
		name: "me_auto-lisp-scripting-language",
		uri: {
			light: "/assets/icons/me/auto-lisp-scripting-language.png",
			dark: "/assets/icons/me/auto-lisp-scripting-language.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_autocad: {
		name: "me_autocad",
		uri: {
			light: "/assets/icons/me/autocad.png",
			dark: "/assets/icons/me/autocad.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"me_center-of-gravity": {
		name: "me_center-of-gravity",
		uri: {
			light: "/assets/icons/me/center-of-gravity.png",
			dark: "/assets/icons/me/center-of-gravity.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_cog: {
		name: "me_cog",
		uri: {
			light: "/assets/icons/me/cog-light.png",
			dark: "/assets/icons/me/cog-dark.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_cogs: {
		name: "me_cogs",
		uri: {
			light: "/assets/icons/me/cogs.png",
			dark: "/assets/icons/me/cogs.png",
		},
		info: {
			height: 128,
			width: 217,
			type: "png",
			ratio: 1.7,
		},
	},
	"me_esprit-by-dp-technology": {
		name: "me_esprit-by-dp-technology",
		uri: {
			light: "/assets/icons/me/esprit-by-dp-technology.png",
			dark: "/assets/icons/me/esprit-by-dp-technology.png",
		},
		info: {
			height: 128,
			width: 403,
			type: "png",
			ratio: 3.15,
		},
	},
	"me_esprit-square": {
		name: "me_esprit-square",
		uri: {
			light: "/assets/icons/me/esprit-square.png",
			dark: "/assets/icons/me/esprit-square.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_haas: {
		name: "me_haas",
		uri: {
			light: "/assets/icons/me/haas.png",
			dark: "/assets/icons/me/haas.png",
		},
		info: {
			height: 242,
			width: 300,
			type: "png",
			ratio: 1.24,
		},
	},
	"me_iso-g-code": {
		name: "me_iso-g-code",
		uri: {
			light: "/assets/icons/me/iso-g-code.png",
			dark: "/assets/icons/me/iso-g-code.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_machining: {
		name: "me_machining",
		uri: {
			light: "/assets/icons/me/machining-light.png",
			dark: "/assets/icons/me/machining.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"me_mathcad-icon": {
		name: "me_mathcad-icon",
		uri: {
			light: "/assets/icons/me/mathcad-icon.png",
			dark: "/assets/icons/me/mathcad-icon.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_matlab: {
		name: "me_matlab",
		uri: {
			light: "/assets/icons/me/matlab.svg",
			dark: "/assets/icons/me/matlab.svg",
		},
		info: {
			height: 800,
			width: 800,
			type: "svg",
			ratio: 1,
		},
	},
	me_mazak: {
		name: "me_mazak",
		uri: {
			light: "/assets/icons/me/mazak.png",
			dark: "/assets/icons/me/mazak.png",
		},
		info: {
			height: 128,
			width: 258,
			type: "png",
			ratio: 2.02,
		},
	},
	"me_mechanical-engineering-orantge": {
		name: "me_mechanical-engineering-orantge",
		uri: {
			light: "/assets/icons/me/mechanical-engineering-orantge.png",
			dark: "/assets/icons/me/mechanical-engineering-orantge.png",
		},
		info: {
			height: 128,
			width: 178,
			type: "png",
			ratio: 1.39,
		},
	},
	"me_mechanical-engineering": {
		name: "me_mechanical-engineering",
		uri: {
			light: "/assets/icons/me/mechanical-engineering.png",
			dark: "/assets/icons/me/mechanical-engineering.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"me_nakamura-tome": {
		name: "me_nakamura-tome",
		uri: {
			light: "/assets/icons/me/nakamura-tome.png",
			dark: "/assets/icons/me/nakamura-tome.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"me_proEngineer-ptc-creo-square": {
		name: "me_proEngineer-ptc-creo-square",
		uri: {
			light: "/assets/icons/me/proEngineer-ptc-creo-square.png",
			dark: "/assets/icons/me/proEngineer-ptc-creo-square.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"me_proEngineer-ptc-creo": {
		name: "me_proEngineer-ptc-creo",
		uri: {
			light: "/assets/icons/me/proEngineer-ptc-creo.png",
			dark: "/assets/icons/me/proEngineer-ptc-creo.png",
		},
		info: {
			height: 170,
			width: 152,
			type: "png",
			ratio: 0.89,
		},
	},
	me_serverless: {
		name: "me_serverless",
		uri: {
			light: "/assets/icons/me/serverless.svg",
			dark: "/assets/icons/me/serverless.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"me_sketch-up": {
		name: "me_sketch-up",
		uri: {
			light: "/assets/icons/me/sketch-up.png",
			dark: "/assets/icons/me/sketch-up.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_solidWorks: {
		name: "me_solidWorks",
		uri: {
			light: "/assets/icons/me/solidWorks.png",
			dark: "/assets/icons/me/solidWorks.png",
		},
		info: {
			height: 108,
			width: 108,
			type: "png",
			ratio: 1,
		},
	},
	"me_topsolid-alt": {
		name: "me_topsolid-alt",
		uri: {
			light: "/assets/icons/me/topsolid-alt-light.svg",
			dark: "/assets/icons/me/topsolid-alt-dark.svg",
		},
		info: {
			height: 237,
			width: 600,
			type: "svg",
			ratio: 2.53,
		},
	},
	me_topsolid: {
		name: "me_topsolid",
		uri: {
			light: "/assets/icons/me/topsolid-light.svg",
			dark: "/assets/icons/me/topsolid-dark.svg",
		},
		info: {
			height: 148,
			width: 600,
			type: "svg",
			ratio: 4.05,
		},
	},
	"me_topsolid-favicon": {
		name: "me_topsolid-favicon",
		uri: {
			light: "/assets/icons/me/topsolid-favicon.png",
			dark: "/assets/icons/me/topsolid-favicon.png",
		},
		info: {
			height: 32,
			width: 32,
			type: "png",
			ratio: 1,
		},
	},
	"me_topsolid-single": {
		name: "me_topsolid-single",
		uri: {
			light: "/assets/icons/me/topsolid-single.png",
			dark: "/assets/icons/me/topsolid-single.png",
		},
		info: {
			height: 128,
			width: 424,
			type: "png",
			ratio: 3.31,
		},
	},
	"me_vb-script": {
		name: "me_vb-script",
		uri: {
			light: "/assets/icons/me/vb-script.png",
			dark: "/assets/icons/me/vb-script.png",
		},
		info: {
			height: 593,
			width: 500,
			type: "png",
			ratio: 0.84,
		},
	},
	"me_vector-erp-logo-square": {
		name: "me_vector-erp-logo-square",
		uri: {
			light: "/assets/icons/me/vector-erp-logo-square.png",
			dark: "/assets/icons/me/vector-erp-logo-square.png",
		},
		info: {
			height: 142,
			width: 142,
			type: "png",
			ratio: 1,
		},
	},
	"me_vector-erp-logo": {
		name: "me_vector-erp-logo",
		uri: {
			light: "/assets/icons/me/vector-erp-logo.svg",
			dark: "/assets/icons/me/vector-erp-logo.svg",
		},
		info: {
			height: 230,
			width: 270,
			type: "svg",
			ratio: 1.17,
		},
	},
	"of_adobe-illustrator": {
		name: "of_adobe-illustrator",
		uri: {
			light: "/assets/icons/of/adobe-illustrator.svg",
			dark: "/assets/icons/of/adobe-illustrator.svg",
		},
		info: {
			height: 234,
			width: 240,
			type: "svg",
			ratio: 1.03,
		},
	},
	"of_adobe-photoshop": {
		name: "of_adobe-photoshop",
		uri: {
			light: "/assets/icons/of/adobe-photoshop.svg",
			dark: "/assets/icons/of/adobe-photoshop.svg",
		},
		info: {
			height: 234,
			width: 240,
			type: "svg",
			ratio: 1.03,
		},
	},
	"of_camtasia-circle": {
		name: "of_camtasia-circle",
		uri: {
			light: "/assets/icons/of/camtasia-circle.png",
			dark: "/assets/icons/of/camtasia-circle.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"of_camtasia-square": {
		name: "of_camtasia-square",
		uri: {
			light: "/assets/icons/of/camtasia-square.png",
			dark: "/assets/icons/of/camtasia-square.png",
		},
		info: {
			height: 87,
			width: 87,
			type: "png",
			ratio: 1,
		},
	},
	of_gimp: {
		name: "of_gimp",
		uri: {
			light: "/assets/icons/of/gimp.svg",
			dark: "/assets/icons/of/gimp.svg",
		},
		info: {
			height: 316,
			width: 316,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-access": {
		name: "of_ms-access",
		uri: {
			light: "/assets/icons/of/ms-access.svg",
			dark: "/assets/icons/of/ms-access.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-excel": {
		name: "of_ms-excel",
		uri: {
			light: "/assets/icons/of/ms-excel.svg",
			dark: "/assets/icons/of/ms-excel.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-info": {
		name: "of_ms-info",
		uri: {
			light: "/assets/icons/of/ms-info.svg",
			dark: "/assets/icons/of/ms-info.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-lync": {
		name: "of_ms-lync",
		uri: {
			light: "/assets/icons/of/ms-lync.svg",
			dark: "/assets/icons/of/ms-lync.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-microsoft": {
		name: "of_ms-microsoft",
		uri: {
			light: "/assets/icons/of/ms-microsoft.svg",
			dark: "/assets/icons/of/ms-microsoft.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-ms": {
		name: "of_ms-ms",
		uri: {
			light: "/assets/icons/of/ms-ms.svg",
			dark: "/assets/icons/of/ms-ms.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-one-note": {
		name: "of_ms-one-note",
		uri: {
			light: "/assets/icons/of/ms-one-note.svg",
			dark: "/assets/icons/of/ms-one-note.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-outlook": {
		name: "of_ms-outlook",
		uri: {
			light: "/assets/icons/of/ms-outlook.svg",
			dark: "/assets/icons/of/ms-outlook.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-powerpoint": {
		name: "of_ms-powerpoint",
		uri: {
			light: "/assets/icons/of/ms-powerpoint.svg",
			dark: "/assets/icons/of/ms-powerpoint.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-professional": {
		name: "of_ms-professional",
		uri: {
			light: "/assets/icons/of/ms-professional.svg",
			dark: "/assets/icons/of/ms-professional.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-publisher": {
		name: "of_ms-publisher",
		uri: {
			light: "/assets/icons/of/ms-publisher.svg",
			dark: "/assets/icons/of/ms-publisher.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-word": {
		name: "of_ms-word",
		uri: {
			light: "/assets/icons/of/ms-word.svg",
			dark: "/assets/icons/of/ms-word.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_obs-studio": {
		name: "of_obs-studio",
		uri: {
			light: "/assets/icons/of/obs-studio.webp",
			dark: "/assets/icons/of/obs-studio.webp",
		},
		info: {
			height: 256,
			width: 256,
			type: "webp",
			ratio: 1,
		},
	},
	"of_obs-studio_x128-png": {
		name: "of_obs-studio_x128-png",
		uri: {
			light: "/assets/icons/of/obs-studio_x128-png.png",
			dark: "/assets/icons/of/obs-studio_x128-png.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"of_obs-studio_x128": {
		name: "of_obs-studio_x128",
		uri: {
			light: "/assets/icons/of/obs-studio_x128.webp",
			dark: "/assets/icons/of/obs-studio_x128.webp",
		},
		info: {
			height: 128,
			width: 128,
			type: "webp",
			ratio: 1,
		},
	},
	"ui_angles-up-down-reverse-close": {
		name: "ui_angles-up-down-reverse-close",
		uri: {
			light: "/assets/icons/ui/angles-up-down-reverse-close.svg",
			dark: "/assets/icons/ui/angles-up-down-reverse-close.svg",
		},
		info: {
			height: 16,
			width: 14,
			type: "svg",
			ratio: 0.88,
		},
	},
	"ui_angles-up-down-reverse": {
		name: "ui_angles-up-down-reverse",
		uri: {
			light: "/assets/icons/ui/angles-up-down-reverse.svg",
			dark: "/assets/icons/ui/angles-up-down-reverse.svg",
		},
		info: {
			height: 16,
			width: 14,
			type: "svg",
			ratio: 0.88,
		},
	},
	"ui_angles-up-down": {
		name: "ui_angles-up-down",
		uri: {
			light: "/assets/icons/ui/angles-up-down.svg",
			dark: "/assets/icons/ui/angles-up-down.svg",
		},
		info: {
			height: 16,
			width: 14,
			type: "svg",
			ratio: 0.88,
		},
	},
	"ui_domain-www-icon": {
		name: "ui_domain-www-icon",
		uri: {
			light: "/assets/icons/ui/domain-www-icon-light.svg",
			dark: "/assets/icons/ui/domain-www-icon-dark.svg",
		},
		info: {
			height: 91,
			width: 123,
			type: "svg",
			ratio: 1.35,
		},
	},
	ui_fingerprint: {
		name: "ui_fingerprint",
		uri: {
			light: "/assets/icons/ui/fingerprint.svg",
			dark: "/assets/icons/ui/fingerprint.svg",
		},
		info: {
			height: 745,
			width: 808,
			type: "svg",
			ratio: 1.08,
		},
	},
	ui_google: {
		name: "ui_google",
		uri: {
			light: "/assets/icons/ui/google.svg",
			dark: "/assets/icons/ui/google.svg",
		},
		info: {
			height: 191,
			width: 187,
			type: "svg",
			ratio: 0.98,
		},
	},
	"ui_i-download-cv": {
		name: "ui_i-download-cv",
		uri: {
			light: "/assets/icons/ui/i-download-cv.svg",
			dark: "/assets/icons/ui/i-download-cv.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	"ui_i-save-business-card": {
		name: "ui_i-save-business-card",
		uri: {
			light: "/assets/icons/ui/i-save-business-card.svg",
			dark: "/assets/icons/ui/i-save-business-card.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	"ui_i-send-email": {
		name: "ui_i-send-email",
		uri: {
			light: "/assets/icons/ui/i-send-email.svg",
			dark: "/assets/icons/ui/i-send-email.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	ui_link: {
		name: "ui_link",
		uri: {
			light: "/assets/icons/ui/link.svg",
			dark: "/assets/icons/ui/link.svg",
		},
		info: {
			height: 24,
			width: 24,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_linked-in-gray-square": {
		name: "ui_linked-in-gray-square",
		uri: {
			light: "/assets/icons/ui/linked-in-gray-square.svg",
			dark: "/assets/icons/ui/linked-in-gray-square.svg",
		},
		info: {
			height: 512,
			width: 448,
			type: "svg",
			ratio: 0.88,
		},
	},
	ui_loader: {
		name: "ui_loader",
		uri: {
			light: "/assets/icons/ui/loader.svg",
			dark: "/assets/icons/ui/loader.svg",
		},
		info: {
			height: 200,
			width: 200,
			type: "svg",
			ratio: 1,
		},
	},
	ui_menu: {
		name: "ui_menu",
		uri: {
			light: "/assets/icons/ui/menu.svg",
			dark: "/assets/icons/ui/menu.svg",
		},
		info: {
			height: 30,
			width: 30,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_star-half-stroke": {
		name: "ui_star-half-stroke",
		uri: {
			light: "/assets/icons/ui/star-half-stroke.svg",
			dark: "/assets/icons/ui/star-half-stroke.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	"ui_star-stroke": {
		name: "ui_star-stroke",
		uri: {
			light: "/assets/icons/ui/star-stroke.svg",
			dark: "/assets/icons/ui/star-stroke.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	ui_star: {
		name: "ui_star",
		uri: {
			light: "/assets/icons/ui/star.svg",
			dark: "/assets/icons/ui/star.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	ui_tick: {
		name: "ui_tick",
		uri: {
			light: "/assets/icons/ui/tick.svg",
			dark: "/assets/icons/ui/tick.svg",
		},
		info: {
			height: 14,
			width: 14,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_trivictoria-logo": {
		name: "ui_trivictoria-logo",
		uri: {
			light: "/assets/icons/ui/trivictoria-logo.svg",
			dark: "/assets/icons/ui/trivictoria-logo.svg",
		},
		info: {
			height: 707,
			width: 707,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_ubuntu-gray": {
		name: "ui_ubuntu-gray",
		uri: {
			light: "/assets/icons/ui/ubuntu-gray.svg",
			dark: "/assets/icons/ui/ubuntu-gray.svg",
		},
		info: {
			height: 512,
			width: 496,
			type: "svg",
			ratio: 0.97,
		},
	},
	"ui_user-graduate-fa-dt": {
		name: "ui_user-graduate-fa-dt",
		uri: {
			light: "/assets/icons/ui/user-graduate-fa-dt.svg",
			dark: "/assets/icons/ui/user-graduate-fa-dt.svg",
		},
		info: {
			height: 16,
			width: 14,
			type: "svg",
			ratio: 0.88,
		},
	},
	"ui_user-secret-fa-dt": {
		name: "ui_user-secret-fa-dt",
		uri: {
			light: "/assets/icons/ui/user-secret-fa-dt.svg",
			dark: "/assets/icons/ui/user-secret-fa-dt.svg",
		},
		info: {
			height: 16,
			width: 14,
			type: "svg",
			ratio: 0.88,
		},
	},
	"ui_wikimedia-gray": {
		name: "ui_wikimedia-gray",
		uri: {
			light: "/assets/icons/ui/wikimedia-gray.svg",
			dark: "/assets/icons/ui/wikimedia-gray.svg",
		},
		info: {
			height: 897,
			width: 900,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_www-icon": {
		name: "ui_www-icon",
		uri: {
			light: "/assets/icons/ui/www-icon-light.svg",
			dark: "/assets/icons/ui/www-icon-dark.svg",
		},
		info: {
			height: 80,
			width: 123,
			type: "svg",
			ratio: 1.54,
		},
	},
	placeholder: {
		name: "placeholder",
		uri: {
			light: "/assets/icons/placeholder.svg",
			dark: "/assets/icons/placeholder.svg",
		},
		info: {
			height: 434,
			width: 512,
			type: "svg",
			ratio: 1.18,
		},
	},
};

export default iconsMap;

export type IconsMapItem = keyof typeof iconsMap;
