// This file is generated by scripts/generate-icon-map.ts

const iconsMap = {
	babel2: {
		name: "babel2",
		light: "/assets/icons/babel2-light.svg",
		dark: "/assets/icons/babel2-light.svg",
	},
	javascript: {
		name: "javascript",
		light: "/assets/icons/javascript.svg",
		dark: "/assets/icons/javascript.svg",
	},
	prettier: {
		name: "prettier",
		light: "/assets/icons/prettier-light.svg",
		dark: "/assets/icons/prettier.svg",
	},
	prisma: {
		name: "prisma",
		light: "/assets/icons/prisma-light.svg",
		dark: "/assets/icons/prisma.svg",
	},
	solidworks: {
		name: "solidworks",
		light: "/assets/icons/solidworks.png",
		dark: "/assets/icons/solidworks.png",
	},
	typescript: {
		name: "typescript",
		light: "/assets/icons/typescript.svg",
		dark: "/assets/icons/typescript.svg",
	},
};

export default iconsMap;
