// This file is generated by scripts/generate-icon-map.ts

const iconsMap = {
	"it_PHP-logo": {
		name: "it_PHP-logo",
		uri: {
			light: "/assets/icons/it/PHP-logo.svg",
			dark: "/assets/icons/it/PHP-logo.svg",
		},
		info: {
			height: 384,
			width: 711,
			type: "svg",
			ratio: 1.85,
		},
	},
	it_babel2: {
		name: "it_babel2",
		uri: {
			light: "/assets/icons/it/babel2-light.svg",
			dark: "/assets/icons/it/babel2-light.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_javascript: {
		name: "it_javascript",
		uri: {
			light: "/assets/icons/it/javascript.svg",
			dark: "/assets/icons/it/javascript.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_mongo: {
		name: "it_mongo",
		uri: {
			light: "/assets/icons/it/mongo.svg",
			dark: "/assets/icons/it/mongo.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_mongoosejs-favicon": {
		name: "it_mongoosejs-favicon",
		uri: {
			light: "/assets/icons/it/mongoosejs-favicon.png",
			dark: "/assets/icons/it/mongoosejs-favicon.png",
		},
		info: {
			height: 144,
			width: 144,
			type: "png",
			ratio: 1,
		},
	},
	it_mongoosejs: {
		name: "it_mongoosejs",
		uri: {
			light: "/assets/icons/it/mongoosejs.png",
			dark: "/assets/icons/it/mongoosejs.png",
		},
		info: {
			height: 200,
			width: 200,
			type: "png",
			ratio: 1,
		},
	},
	"it_new-php-logo": {
		name: "it_new-php-logo",
		uri: {
			light: "/assets/icons/it/new-php-logo.svg",
			dark: "/assets/icons/it/new-php-logo.svg",
		},
		info: {
			height: 384,
			width: 711,
			type: "svg",
			ratio: 1.85,
		},
	},
	"it_nextjs-icon": {
		name: "it_nextjs-icon",
		uri: {
			light: "/assets/icons/it/nextjs-icon-light.svg",
			dark: "/assets/icons/it/nextjs-icon-dark.svg",
		},
		info: {
			height: 180,
			width: 180,
			type: "svg",
			ratio: 1,
		},
	},
	it_node: {
		name: "it_node",
		uri: {
			light: "/assets/icons/it/node.svg",
			dark: "/assets/icons/it/node.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_node2: {
		name: "it_node2",
		uri: {
			light: "/assets/icons/it/node2.svg",
			dark: "/assets/icons/it/node2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_php-fa": {
		name: "it_php-fa",
		uri: {
			light: "/assets/icons/it/php-fa-light.svg",
			dark: "/assets/icons/it/php-fa-dark.svg",
		},
		info: {
			height: 16,
			width: 20,
			type: "svg",
			ratio: 1.25,
		},
	},
	it_php: {
		name: "it_php",
		uri: {
			light: "/assets/icons/it/php.svg",
			dark: "/assets/icons/it/php.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_php2: {
		name: "it_php2",
		uri: {
			light: "/assets/icons/it/php2.svg",
			dark: "/assets/icons/it/php2.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_php3: {
		name: "it_php3",
		uri: {
			light: "/assets/icons/it/php3.svg",
			dark: "/assets/icons/it/php3.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_prettier: {
		name: "it_prettier",
		uri: {
			light: "/assets/icons/it/prettier-light.svg",
			dark: "/assets/icons/it/prettier.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_prisma: {
		name: "it_prisma",
		uri: {
			light: "/assets/icons/it/prisma-light.svg",
			dark: "/assets/icons/it/prisma.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	it_typescript: {
		name: "it_typescript",
		uri: {
			light: "/assets/icons/it/typescript.svg",
			dark: "/assets/icons/it/typescript.svg",
		},
		info: {
			height: 32,
			width: 32,
			type: "svg",
			ratio: 1,
		},
	},
	"it_vercel-icon": {
		name: "it_vercel-icon",
		uri: {
			light: "/assets/icons/it/vercel-icon-light.svg",
			dark: "/assets/icons/it/vercel-icon-dark.svg",
		},
		info: {
			height: 1000,
			width: 1155,
			type: "svg",
			ratio: 1.16,
		},
	},
	"me_auto-lisp-scripting-language": {
		name: "me_auto-lisp-scripting-language",
		uri: {
			light: "/assets/icons/me/auto-lisp-scripting-language.png",
			dark: "/assets/icons/me/auto-lisp-scripting-language.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_autocad: {
		name: "me_autocad",
		uri: {
			light: "/assets/icons/me/autocad.png",
			dark: "/assets/icons/me/autocad.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"me_center-of-gravity": {
		name: "me_center-of-gravity",
		uri: {
			light: "/assets/icons/me/center-of-gravity.png",
			dark: "/assets/icons/me/center-of-gravity.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_cog: {
		name: "me_cog",
		uri: {
			light: "/assets/icons/me/cog-light.png",
			dark: "/assets/icons/me/cog-dark.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_cogs: {
		name: "me_cogs",
		uri: {
			light: "/assets/icons/me/cogs.png",
			dark: "/assets/icons/me/cogs.png",
		},
		info: {
			height: 128,
			width: 217,
			type: "png",
			ratio: 1.7,
		},
	},
	"me_esprit-by-dp-technology": {
		name: "me_esprit-by-dp-technology",
		uri: {
			light: "/assets/icons/me/esprit-by-dp-technology.png",
			dark: "/assets/icons/me/esprit-by-dp-technology.png",
		},
		info: {
			height: 128,
			width: 403,
			type: "png",
			ratio: 3.15,
		},
	},
	"me_esprit-square": {
		name: "me_esprit-square",
		uri: {
			light: "/assets/icons/me/esprit-square.png",
			dark: "/assets/icons/me/esprit-square.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_haas: {
		name: "me_haas",
		uri: {
			light: "/assets/icons/me/haas.png",
			dark: "/assets/icons/me/haas.png",
		},
		info: {
			height: 242,
			width: 300,
			type: "png",
			ratio: 1.24,
		},
	},
	"me_iso-g-code": {
		name: "me_iso-g-code",
		uri: {
			light: "/assets/icons/me/iso-g-code.png",
			dark: "/assets/icons/me/iso-g-code.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_machining: {
		name: "me_machining",
		uri: {
			light: "/assets/icons/me/machining-light.png",
			dark: "/assets/icons/me/machining.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"me_mathcad-icon": {
		name: "me_mathcad-icon",
		uri: {
			light: "/assets/icons/me/mathcad-icon.png",
			dark: "/assets/icons/me/mathcad-icon.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_matlab: {
		name: "me_matlab",
		uri: {
			light: "/assets/icons/me/matlab.svg",
			dark: "/assets/icons/me/matlab.svg",
		},
		info: {
			height: 800,
			width: 800,
			type: "svg",
			ratio: 1,
		},
	},
	me_mazak: {
		name: "me_mazak",
		uri: {
			light: "/assets/icons/me/mazak.png",
			dark: "/assets/icons/me/mazak.png",
		},
		info: {
			height: 128,
			width: 258,
			type: "png",
			ratio: 2.02,
		},
	},
	"me_mechanical-engineering-orantge": {
		name: "me_mechanical-engineering-orantge",
		uri: {
			light: "/assets/icons/me/mechanical-engineering-orantge.png",
			dark: "/assets/icons/me/mechanical-engineering-orantge.png",
		},
		info: {
			height: 128,
			width: 178,
			type: "png",
			ratio: 1.39,
		},
	},
	"me_mechanical-engineering": {
		name: "me_mechanical-engineering",
		uri: {
			light: "/assets/icons/me/mechanical-engineering.png",
			dark: "/assets/icons/me/mechanical-engineering.png",
		},
		info: {
			height: 512,
			width: 512,
			type: "png",
			ratio: 1,
		},
	},
	"me_proEngineer-ptc-creo-square": {
		name: "me_proEngineer-ptc-creo-square",
		uri: {
			light: "/assets/icons/me/proEngineer-ptc-creo-square.png",
			dark: "/assets/icons/me/proEngineer-ptc-creo-square.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	"me_proEngineer-ptc-creo": {
		name: "me_proEngineer-ptc-creo",
		uri: {
			light: "/assets/icons/me/proEngineer-ptc-creo.png",
			dark: "/assets/icons/me/proEngineer-ptc-creo.png",
		},
		info: {
			height: 170,
			width: 152,
			type: "png",
			ratio: 0.89,
		},
	},
	"me_sketch-up": {
		name: "me_sketch-up",
		uri: {
			light: "/assets/icons/me/sketch-up.png",
			dark: "/assets/icons/me/sketch-up.png",
		},
		info: {
			height: 128,
			width: 128,
			type: "png",
			ratio: 1,
		},
	},
	me_solidWorks: {
		name: "me_solidWorks",
		uri: {
			light: "/assets/icons/me/solidWorks.png",
			dark: "/assets/icons/me/solidWorks.png",
		},
		info: {
			height: 108,
			width: 108,
			type: "png",
			ratio: 1,
		},
	},
	"me_topsolid-alt": {
		name: "me_topsolid-alt",
		uri: {
			light: "/assets/icons/me/topsolid-alt-light.svg",
			dark: "/assets/icons/me/topsolid-alt-dark.svg",
		},
		info: {
			height: 237,
			width: 600,
			type: "svg",
			ratio: 2.53,
		},
	},
	me_topsolid: {
		name: "me_topsolid",
		uri: {
			light: "/assets/icons/me/topsolid-light.svg",
			dark: "/assets/icons/me/topsolid-dark.svg",
		},
		info: {
			height: 148,
			width: 600,
			type: "svg",
			ratio: 4.05,
		},
	},
	"me_topsolid-favicon": {
		name: "me_topsolid-favicon",
		uri: {
			light: "/assets/icons/me/topsolid-favicon.png",
			dark: "/assets/icons/me/topsolid-favicon.png",
		},
		info: {
			height: 32,
			width: 32,
			type: "png",
			ratio: 1,
		},
	},
	"me_topsolid-single": {
		name: "me_topsolid-single",
		uri: {
			light: "/assets/icons/me/topsolid-single.png",
			dark: "/assets/icons/me/topsolid-single.png",
		},
		info: {
			height: 128,
			width: 424,
			type: "png",
			ratio: 3.31,
		},
	},
	"me_vb-script": {
		name: "me_vb-script",
		uri: {
			light: "/assets/icons/me/vb-script.png",
			dark: "/assets/icons/me/vb-script.png",
		},
		info: {
			height: 593,
			width: 500,
			type: "png",
			ratio: 0.84,
		},
	},
	"me_vector-erp-logo-square": {
		name: "me_vector-erp-logo-square",
		uri: {
			light: "/assets/icons/me/vector-erp-logo-square.png",
			dark: "/assets/icons/me/vector-erp-logo-square.png",
		},
		info: {
			height: 142,
			width: 142,
			type: "png",
			ratio: 1,
		},
	},
	"me_vector-erp-logo": {
		name: "me_vector-erp-logo",
		uri: {
			light: "/assets/icons/me/vector-erp-logo.svg",
			dark: "/assets/icons/me/vector-erp-logo.svg",
		},
		info: {
			height: 230,
			width: 270,
			type: "svg",
			ratio: 1.17,
		},
	},
	"of_adobe-illustrator": {
		name: "of_adobe-illustrator",
		uri: {
			light: "/assets/icons/of/adobe-illustrator.svg",
			dark: "/assets/icons/of/adobe-illustrator.svg",
		},
		info: {
			height: 234,
			width: 240,
			type: "svg",
			ratio: 1.03,
		},
	},
	"of_adobe-photoshop": {
		name: "of_adobe-photoshop",
		uri: {
			light: "/assets/icons/of/adobe-photoshop.svg",
			dark: "/assets/icons/of/adobe-photoshop.svg",
		},
		info: {
			height: 234,
			width: 240,
			type: "svg",
			ratio: 1.03,
		},
	},
	of_gimp: {
		name: "of_gimp",
		uri: {
			light: "/assets/icons/of/gimp.svg",
			dark: "/assets/icons/of/gimp.svg",
		},
		info: {
			height: 316,
			width: 316,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-access": {
		name: "of_ms-access",
		uri: {
			light: "/assets/icons/of/ms-access.svg",
			dark: "/assets/icons/of/ms-access.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-excel": {
		name: "of_ms-excel",
		uri: {
			light: "/assets/icons/of/ms-excel.svg",
			dark: "/assets/icons/of/ms-excel.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-info": {
		name: "of_ms-info",
		uri: {
			light: "/assets/icons/of/ms-info.svg",
			dark: "/assets/icons/of/ms-info.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-lync": {
		name: "of_ms-lync",
		uri: {
			light: "/assets/icons/of/ms-lync.svg",
			dark: "/assets/icons/of/ms-lync.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-microsoft": {
		name: "of_ms-microsoft",
		uri: {
			light: "/assets/icons/of/ms-microsoft.svg",
			dark: "/assets/icons/of/ms-microsoft.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-ms": {
		name: "of_ms-ms",
		uri: {
			light: "/assets/icons/of/ms-ms.svg",
			dark: "/assets/icons/of/ms-ms.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-one-note": {
		name: "of_ms-one-note",
		uri: {
			light: "/assets/icons/of/ms-one-note.svg",
			dark: "/assets/icons/of/ms-one-note.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-outlook": {
		name: "of_ms-outlook",
		uri: {
			light: "/assets/icons/of/ms-outlook.svg",
			dark: "/assets/icons/of/ms-outlook.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-powerpoint": {
		name: "of_ms-powerpoint",
		uri: {
			light: "/assets/icons/of/ms-powerpoint.svg",
			dark: "/assets/icons/of/ms-powerpoint.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-professional": {
		name: "of_ms-professional",
		uri: {
			light: "/assets/icons/of/ms-professional.svg",
			dark: "/assets/icons/of/ms-professional.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-publisher": {
		name: "of_ms-publisher",
		uri: {
			light: "/assets/icons/of/ms-publisher.svg",
			dark: "/assets/icons/of/ms-publisher.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	"of_ms-word": {
		name: "of_ms-word",
		uri: {
			light: "/assets/icons/of/ms-word.svg",
			dark: "/assets/icons/of/ms-word.svg",
		},
		info: {
			height: 667,
			width: 667,
			type: "svg",
			ratio: 1,
		},
	},
	ui_fingerprint: {
		name: "ui_fingerprint",
		uri: {
			light: "/assets/icons/ui/fingerprint.svg",
			dark: "/assets/icons/ui/fingerprint.svg",
		},
		info: {
			height: 745,
			width: 808,
			type: "svg",
			ratio: 1.08,
		},
	},
	"ui_github-gray": {
		name: "ui_github-gray",
		uri: {
			light: "/assets/icons/ui/github-gray.svg",
			dark: "/assets/icons/ui/github-gray.svg",
		},
		info: {
			height: 512,
			width: 496,
			type: "svg",
			ratio: 0.97,
		},
	},
	ui_github: {
		name: "ui_github",
		uri: {
			light: "/assets/icons/ui/github.svg",
			dark: "/assets/icons/ui/github.svg",
		},
		info: {
			height: 512,
			width: 496,
			type: "svg",
			ratio: 0.97,
		},
	},
	ui_google: {
		name: "ui_google",
		uri: {
			light: "/assets/icons/ui/google.svg",
			dark: "/assets/icons/ui/google.svg",
		},
		info: {
			height: 191,
			width: 187,
			type: "svg",
			ratio: 0.98,
		},
	},
	"ui_i-download-cv": {
		name: "ui_i-download-cv",
		uri: {
			light: "/assets/icons/ui/i-download-cv.svg",
			dark: "/assets/icons/ui/i-download-cv.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	"ui_i-save-business-card": {
		name: "ui_i-save-business-card",
		uri: {
			light: "/assets/icons/ui/i-save-business-card.svg",
			dark: "/assets/icons/ui/i-save-business-card.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	"ui_i-send-email": {
		name: "ui_i-send-email",
		uri: {
			light: "/assets/icons/ui/i-send-email.svg",
			dark: "/assets/icons/ui/i-send-email.svg",
		},
		info: {
			height: 448,
			width: 576,
			type: "svg",
			ratio: 1.29,
		},
	},
	ui_link: {
		name: "ui_link",
		uri: {
			light: "/assets/icons/ui/link.svg",
			dark: "/assets/icons/ui/link.svg",
		},
		info: {
			height: 24,
			width: 24,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_linked-in-gray-square": {
		name: "ui_linked-in-gray-square",
		uri: {
			light: "/assets/icons/ui/linked-in-gray-square.svg",
			dark: "/assets/icons/ui/linked-in-gray-square.svg",
		},
		info: {
			height: 512,
			width: 448,
			type: "svg",
			ratio: 0.88,
		},
	},
	ui_loader: {
		name: "ui_loader",
		uri: {
			light: "/assets/icons/ui/loader.svg",
			dark: "/assets/icons/ui/loader.svg",
		},
		info: {
			height: 200,
			width: 200,
			type: "svg",
			ratio: 1,
		},
	},
	ui_menu: {
		name: "ui_menu",
		uri: {
			light: "/assets/icons/ui/menu.svg",
			dark: "/assets/icons/ui/menu.svg",
		},
		info: {
			height: 30,
			width: 30,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_star-half-stroke": {
		name: "ui_star-half-stroke",
		uri: {
			light: "/assets/icons/ui/star-half-stroke.svg",
			dark: "/assets/icons/ui/star-half-stroke.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	"ui_star-stroke": {
		name: "ui_star-stroke",
		uri: {
			light: "/assets/icons/ui/star-stroke.svg",
			dark: "/assets/icons/ui/star-stroke.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	ui_star: {
		name: "ui_star",
		uri: {
			light: "/assets/icons/ui/star.svg",
			dark: "/assets/icons/ui/star.svg",
		},
		info: {
			height: 512,
			width: 576,
			type: "svg",
			ratio: 1.13,
		},
	},
	ui_tick: {
		name: "ui_tick",
		uri: {
			light: "/assets/icons/ui/tick.svg",
			dark: "/assets/icons/ui/tick.svg",
		},
		info: {
			height: 14,
			width: 14,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_trivictoria-logo": {
		name: "ui_trivictoria-logo",
		uri: {
			light: "/assets/icons/ui/trivictoria-logo.svg",
			dark: "/assets/icons/ui/trivictoria-logo.svg",
		},
		info: {
			height: 707,
			width: 707,
			type: "svg",
			ratio: 1,
		},
	},
	"ui_ubuntu-gray": {
		name: "ui_ubuntu-gray",
		uri: {
			light: "/assets/icons/ui/ubuntu-gray.svg",
			dark: "/assets/icons/ui/ubuntu-gray.svg",
		},
		info: {
			height: 512,
			width: 496,
			type: "svg",
			ratio: 0.97,
		},
	},
	"ui_wikimedia-gray": {
		name: "ui_wikimedia-gray",
		uri: {
			light: "/assets/icons/ui/wikimedia-gray.svg",
			dark: "/assets/icons/ui/wikimedia-gray.svg",
		},
		info: {
			height: 897,
			width: 900,
			type: "svg",
			ratio: 1,
		},
	},
	placeholder: {
		name: "placeholder",
		uri: {
			light: "/assets/icons/placeholder.svg",
			dark: "/assets/icons/placeholder.svg",
		},
		info: {
			height: 434,
			width: 512,
			type: "svg",
			ratio: 1.18,
		},
	},
};

export default iconsMap;

export type IconsMapItem = keyof typeof iconsMap;
